# .github/workflows/snake.yml
name: Generate Snake Car

on:
  schedule: # exécution quotidienne
    - cron: "0 0 * * *"
  workflow_dispatch: # exécution manuelle
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake car animation
        uses: CedricGayraud/snk-car@main 
        with:
          github_user_name: CedricGayraud
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake car animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
